{
 "title": "ClickHouse Metrics via Prometheus",
 "tags": [
  "clickhouse",
  "metrics",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Queries",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clickhouse_system_metrics{metric_name=\"Query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "clickhouse_system_metrics{metric_name=\"MemoryUsage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(clickhouse_system_metrics{metric_name=\"Read\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(clickhouse_system_metrics{metric_name=\"Write\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}