{
 "title": "ClickHouse Monitoring",
 "description": "Мониторинг кластера Clickhouse",
 "tags": [ "Clickhouse" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Время работы (сек)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ClickHouseAsyncMetrics_Uptime" }
   ]
  },
  {
   "title": "Время работы (мин)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_Uptime/60"
    }
   ]
  },
  {
   "title": "Время работы (час)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_Uptime/60/60"
    }
   ]
  },
  {
   "title": "Время работы (день)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_Uptime/60/60/24"
    }
   ]
  },
  { "title": "Нагрузка", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Использование памяти (MB)",
   "type": "timeseries",
   "description": "Текущее использование памяти (MB)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "CPU Virtual Time (μs)",
   "type": "timeseries",
   "description": "CPU Virtual Time (микросекунды)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_OSCPUVirtualTimeMicroseconds[5m])",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Запросы в секунду",
   "type": "timeseries",
   "description": "Insert и Select запросы в секунду",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_SelectQuery[1m])",
     "legendFormat": "SELECT"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_InsertQuery[1m])",
     "legendFormat": "INSERT"
    }
   ]
  },
  {
   "title": "Активные / Очередь запросов",
   "type": "timeseries",
   "description": "Число активных и ожидающих запросов",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ClickHouseMetrics_Query", "legendFormat": "Active Queries" },
    {
     "expr": "clickhouse_metrics_QueuedQueries",
     "legendFormat": "Queued Queries"
    }
   ]
  },
  {
   "title": "Длительность запросов [5м]",
   "type": "timeseries",
   "description": "Длительность SELECT и INSERT запросов",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_SelectQueryTimeMicroseconds{instance=\"clickhouse:9363\"}[5m])",
     "legendFormat": "SELECT"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_InsertQueryTimeMicroseconds{instance=\"clickhouse:9363\"}[5m])",
     "legendFormat": "INSERT"
    }
   ]
  },
  {
   "title": "Запросы",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Количество SELECT запросов",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ClickHouseProfileEvents_SelectQuery",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Количество \"упавших\" запросов",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ClickHouseProfileEvents_FailedQuery",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ошибок в минуту",
     "type": "timeseries",
     "description": "SQL Parsing Errors",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ClickHouseProfileEvents_FailedQuery[1m])",
       "legendFormat": "Parsing Errors/sec"
      }
     ]
    }
   ]
  },
  { "title": "Кафка", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Количество прочитанных строк из Кафка за последнюю  минуту",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaRowsRead[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Скорость чтения сообщений из кафка за посл минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_KafkaMessagesPolled[1m])",
     "legendFormat": "сообщений в сек"
    }
   ]
  },
  {
   "title": "Kafka-lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "sum by (consumergroup, topic) (kafka_consumergroup_lag)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}