FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY exporter.py .

CMD ["gunicorn", "-b", "0.0.0.0:9363", "--access-logfile", "-", "exporter:app"]