FROM clickhouse/clickhouse-server:25.1.3.23

# Установка утилит
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        vim \
        curl \
        libcurl4 \
        ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /var/lib/clickhouse && \
    chown -R clickhouse:clickhouse /var/lib/clickhouse